export const ADMIN_ROUTE = '/admin' 
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const REQUESTS_ROUTE = '/request'
export const SHOP_ROUTE = '/'
export const BOOKS_ROUTE = '/books'
export const DELIVERIES_ROUTE = '/deliveries'
